# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'vs2017-win2016' # examples of other options: 'macOS-10.13', 'ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.16.0'
  displayName: 'Install NodeJS LTS'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    npm install -g @angular/cli@7.x
    npm install
    ng build --prod
  displayName: 'Install Angular 7.x'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'
  displayName: 'Publish Build Artifacts'

#- task: ArchiveFiles@2
#  inputs:
#    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
#    includeRootFolder: false
